baseURL = 'https://xufuja.github.io/'
languageCode = 'en-us'
title = 'A Blog'
paginate = 5
theme = 'PaperMod'
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = UA-123-45

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
title = "A Blog"
description = ""
keywords = [ "Blog" ]
author = "Me"
#images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  disableHLJS = true # to disable highlight.js
  disableFingerprinting = true
  #favicon = "<link / abs url>"
  #favicon16x16 = "<link / abs url>"
  #favicon32x32 = "<link / abs url>"
  #apple_touch_icon = "<link / abs url>"
  #safari_pinned_tab = "<link / abs url>"

  #[params.label]
  #text = "Home"
  #icon = "/apple-touch-icon.png"
  #iconHeight = 35
  
  #[params.profileMode]
  #enabled = false
  #title = "ExampleSite"
  #subtitle = "This is subtitle"
  #imageUrl = "<img location>"
  #imageWidth = 120
  #imageHeight = 120
  #imageTitle = "my image"

    #[[params.profileMode.buttons]]
    #name = "Posts"
    #url = "posts"

    #[[params.profileMode.buttons]]
    #name = "Tags"
    #url = "tags"

  [params.homeInfoParams]
  Title = "A Blog"
  Content = """
Welcome to my blog!
"""

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/Xufuja"

  #[[params.socialIcons]]
  #name = "stackoverflow"
  #url = "https://stackoverflow.com"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/Xufuja"

#[params.analytics.google]
#SiteVerificationTag = "XYZabc"

#[params.analytics.bing]
#SiteVerificationTag = "XYZabc"

#[params.analytics.yandex]
#SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  #[params.editPost]
  #URL = "https://github.com/<path_to_repo>/content"
  #Text = "Suggest Changes"
  #appendFilePath = true

  #[params.fuseOpts]
  #isCaseSensitive = false
  #shouldSort = true
  #location = 0
  #distance = 1_000
  #threshold = 0.4
  #minMatchCharLength = 0
  #keys = [ "title", "permalink", "summary", "content" ]

#[[menu.main]]
#identifier = "categories"
#name = "categories"
#url = "/categories/"
#weight = 10

#[[menu.main]]
#identifier = "tags"
#name = "tags"
#url = "/tags/"
#weight = 20

#[[menu.main]]
#identifier = "example"
#name = "example.org"
#url = "https://example.org"
#weight = 30

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
#anchorLineNos = true
#codeFences = true
#guessSyntax = true
#lineNos = true
#style = "monokai"